name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Extract version from __init__.py
      id: extract_version
      run: |
            python << 'EOF'
            import os
            import re
            
            # 读取 __init__.py
            with open('cvnn_utils/__init__.py', 'r') as f:
                init_content = f.read()
            
            # 提取版本号
            version_match = re.search(r"""__version__\s*=\s*['"]([^'"]+)['"]""", init_content)
            if not version_match:
                raise ValueError("Could not find __version__ in __init__.py")
            
            version = version_match.group(1)
            
            with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
                print(f'version={version}', file=fh)
            EOF
      env:
            PYTHONPATH: ${{ github.workspace }}
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}